### ISSUE TITLE
Guide how to create own cavebot script

### ISSUE THREAD

**Issue by spokom** [MuriloChianfa/TibiaAuto12#44]
Hello

I wanna know how i can add new monsters to the section in cavebot where i can only find rats, orcs etc. Also i gonna be very happy when u add a runemaking option or at least foodeater becouse it seems quite easy to create and it helps a lot for raising mlvls ;D

I love your program man, big thanks for your hard work

**Comment by MuriloChianfa** [comment]
oi amigo, para voce adicionar algum monstro de sua procura, voce deve adicionar uma imagem com o nome do monstro nesta pasta:

![image](https://user-images.githubusercontent.com/60560085/107245231-ad53c700-6a0d-11eb-9183-047773f097c9.png)

because the bot uses these names to attack...
and you must also add names in the 'constants.py' file so that you can choose them in the interface:

![image](https://user-images.githubusercontent.com/60560085/107245594-12a7b800-6a0e-11eb-9249-9cc942c6a759.png)

Just remembering that the names must be the same =D
I hope I helped, and if you need anything else let me know

**Comment by spokom** [comment]
Thanks <3
